#! /bin/sh -e
# /usr/lib/emacsen-common/packages/install/bbdb3

# Written by Jim Van Zandt <jrv@debian.org>, borrowing heavily
# from the install scripts for gettext by Santiago Vila
# <sanvila@ctv.es> and octave by Dirk Eddelbuettel <edd@debian.org>.

FLAVOR=$1
PACKAGE=bbdb3

if [ ${FLAVOR} = emacs ]; then exit 0; fi

# Liberally blacklist unsupported emacsen:
if [ ${FLAVOR} = xemacs19 ]; then exit 0; fi
if [ ${FLAVOR} = xemacs20 ]; then exit 0; fi
if [ ${FLAVOR} = xemacs21 ]; then exit 0; fi
if [ ${FLAVOR} = emacs19 ]; then exit 0; fi
if [ ${FLAVOR} = emacs20 ]; then exit 0; fi
if [ ${FLAVOR} = emacs21 ]; then exit 0; fi
if [ ${FLAVOR} = emacs22 ]; then exit 0; fi
if [ ${FLAVOR} = emacs23 ]; then exit 0; fi

echo install/${PACKAGE}: Handling install for emacsen flavor ${FLAVOR}

#FLAVORTEST=$(echo $FLAVOR | cut -c-6)
#if [ ${FLAVORTEST} = xemacs ] ; then
#    SITEFLAG="-no-site-file"
#else
#    SITEFLAG="--no-site-file"
#fi
FLAGS="${SITEFLAG} --no-init-file --batch --load path.el --funcall batch-byte-compile"

ELDIR=/usr/share/emacs/site-lisp/${PACKAGE}
ELCDIR=/usr/share/${FLAVOR}/site-lisp/${PACKAGE}
ELRELDIR=../../../emacs/site-lisp/${PACKAGE}

# Install-info-altdir does not actually exist.
# Maybe somebody will write it.
if test -x /usr/sbin/install-info-altdir; then
    echo install/${PACKAGE}: install Info links for ${FLAVOR}
    install-info-altdir --quiet --section "" "" --dirname=${FLAVOR} /usr/share/info/${PACKAGE}.info.gz
fi

install -m 755 -d ${ELCDIR}
cd ${ELDIR}
FILES=$(echo *.el)
cd ${ELCDIR}
ln -sf ${ELRELDIR}/*.el .

# do not compile bbdb-pkg.el
FILES="$(echo "$FILES" | sed 's:bbdb-pkg[.]el::')"

# do not compile bbdb-site.el
FILES="$(echo "$FILES" | sed 's:bbdb-site[.]el::')"

# Check if vm is installed for this flavour.
# If not, do not install or compile bbdb-vm.
if test \! -d ../vm; then
    echo "vm seems uninstalled in $FLAVOR, skipping bbdb-vm"
    rm bbdb-vm.el || echo failure to remove bbdb-vm.el
    FILES="$(echo "$FILES" | sed 's:bbdb-vm[.]el::')"
fi

# Check if mu4e is installed for this flavour.
# If not, do not install or compile bbdb-mu4e.
if test \! -d ../mu4e; then
    echo "mu4e seems uninstalled in $FLAVOR, skipping bbdb-mu4e"
    rm bbdb-mu4e.el || echo failure to remove bbdb-mu4e.el
    FILES="$(echo "$FILES" | sed 's:bbdb-mu4e[.]el::')"
fi

cat << EOF > path.el
(debian-pkg-add-load-path-item ".")
(setq byte-compile-warnings nil)
EOF
echo invoking: ${FLAVOR} ${FLAGS} ${FILES}
${FLAVOR} ${FLAGS} ${FILES}
rm -f path.el

exit 0
